# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration, max_jerk]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]

# Easiest way to slow down the robot is to decrease the velocity and acceleration scaling factors
default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0
joint_limits:
  joint_1:
    has_acceleration_limits: false
    has_effort_limits: false
    has_position_limits: true
    has_velocity_limits: true
    has_jerk: false
    max_position: !degrees 170.0
    max_velocity: !degrees 360.0
    min_position: !degrees -170.0
    max_effort: 0.0
  joint_2:
    has_acceleration_limits: false
    has_effort_limits: false
    has_position_limits: true
    has_velocity_limits: true
    has_jerk: false
    max_position: !degrees 45.0
    max_velocity: !degrees 300.0
    min_position: !degrees -190.0
    max_effort: 0.0
  joint_3:
    has_acceleration_limits: false
    has_effort_limits: false
    has_position_limits: true
    has_velocity_limits: true
    has_jerk: false
    max_position: !degrees 156.0
    max_velocity: !degrees 360.0
    min_position: !degrees -120.0
    max_effort: 0.0
  joint_4:
    has_acceleration_limits: false
    has_effort_limits: false
    has_position_limits: true
    has_velocity_limits: true
    has_jerk: false
    max_position: !degrees 185.0
    max_velocity: !degrees 381.0
    min_position: !degrees -185.0
    max_effort: 0.0
  joint_5:
    has_acceleration_limits: false
    has_effort_limits: false
    has_position_limits: true
    has_velocity_limits: true
    has_jerk: false
    max_position: !degrees 120.0
    max_velocity: !degrees 388.0
    min_position: !degrees -120.0
    max_effort: 0.0
  joint_6:
    has_acceleration_limits: false
    has_effort_limits: false
    has_position_limits: true
    has_velocity_limits: true
    has_jerk: false
    max_position: !degrees 350.0
    max_velocity: !degrees 615.0
    min_position: !degrees -350.0
    max_effort: 0.0
