mesh_files:
  base_link:
    visual:
      mesh:
        package: kuka_robot_descriptions
        path: meshes/kr10_r1100_2/visual/base_link.stl
      material:
        name: "KukaPedastal"
        color: "0.5 0.47 0.38 1.0"
    collision:
      mesh:
        package: kuka_robot_descriptions
        path: meshes/kr10_r1100_2/collision/base_link.stl

  link_1:
    visual:
      mesh:
        package: kuka_robot_descriptions
        path: meshes/kr10_r1100_2/visual/link_1.stl
      material:
        name: "KukaOrange"
        color: "0.96 0.47 0.16 1.0"
    collision:
      mesh:
        package: kuka_robot_descriptions
        path: meshes/kr10_r1100_2/collision/link_1.stl

  link_2:
    visual:
      mesh:
        package: kuka_robot_descriptions
        path: meshes/kr10_r1100_2/visual/link_2.stl
      material:
        name: "KukaOrange"
        color: "0.96 0.47 0.16 1.0"
    collision:
      mesh:
        package: kuka_robot_descriptions
        path: meshes/kr10_r1100_2/collision/link_2.stl

  link_3:
    visual:
      mesh:
        package: kuka_robot_descriptions
        path: meshes/kr10_r1100_2/visual/link_3.stl
      material:
        name: "KukaOrange"
        color: "0.96 0.47 0.16 1.0"
    collision:
      mesh:
        package: kuka_robot_descriptions
        path: meshes/kr10_r1100_2/collision/link_3.stl

  link_4:
    visual:
      mesh:
        package: kuka_robot_descriptions
        path: meshes/kr10_r1100_2/visual/link_4.stl
      material:
        name: "KukaOrange"
        color: "0.96 0.47 0.16 1.0"
    collision:
      mesh:
        package: kuka_robot_descriptions
        path: meshes/kr10_r1100_2/collision/link_4.stl

  link_5:
    visual:
      mesh:
        package: kuka_robot_descriptions
        path: meshes/kr10_r1100_2/visual/link_5.stl
      material:
        name: "KukaOrange"
        color: "0.96 0.47 0.16 1.0"
    collision:
      mesh:
        package: kuka_robot_descriptions
        path: meshes/kr10_r1100_2/collision/link_5.stl

  link_6:
    visual:
      mesh:
        package: kuka_robot_descriptions
        path: meshes/kr10_r1100_2/visual/link_6.stl
      material:
        name: "KukaOrange"
        color: "0.96 0.47 0.16 1.0"
    collision:
      mesh:
        package: kuka_robot_descriptions
        path: meshes/kr10_r1100_2/collision/link_6.stl
