# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration, max_jerk]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]

# Easiest way to slow down the robot is to decrease the velocity and acceleration scaling factors
default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0
joint_limits:
  joint_1:
    has_acceleration_limits: false
    has_effort_limits: false
    has_position_limits: true
    has_velocity_limits: true
    has_jerk: false
    max_position: !degrees 185.0
    max_velocity: !degrees 200.0
    min_position: !degrees -185.0
    max_effort: 1905.3
  joint_2:
    has_acceleration_limits: false
    has_effort_limits: false
    has_position_limits: true
    has_velocity_limits: true
    has_jerk: false
    max_position: !degrees 65.0
    max_velocity: !degrees 175.0
    min_position: !degrees -185.0
    max_effort: 1633.625
  joint_3:
    has_acceleration_limits: false
    has_effort_limits: false
    has_position_limits: true
    has_velocity_limits: true
    has_jerk: false
    max_position: !degrees 175.0
    max_velocity: !degrees 190.0
    min_position: !degrees -138.0
    max_effort: 850.58
  joint_4:
    has_acceleration_limits: false
    has_effort_limits: false
    has_position_limits: true
    has_velocity_limits: true
    has_jerk: false
    max_position: !degrees 350.0
    max_velocity: !degrees 430.0
    min_position: !degrees -350.0
    max_effort: 266.210
  joint_5:
    has_acceleration_limits: false
    has_effort_limits: false
    has_position_limits: true
    has_velocity_limits: true
    has_jerk: false
    max_position: !degrees 130.0
    max_velocity: !degrees 430.0
    min_position: !degrees -130.0
    max_effort: 255.43
  joint_6:
    has_acceleration_limits: false
    has_effort_limits: false
    has_position_limits: true
    has_velocity_limits: true
    has_jerk: false
    max_position: !degrees 350.0
    max_velocity: !degrees 630.0
    min_position: !degrees -350.0
    max_effort: 111.657
