mesh_files:
  base_link:
    visual:
      mesh:
        package: kuka_robot_descriptions
        path: meshes/lbr_iisy15_r930/visual/base_link.stl
      material:
        name: "KukaBlack"
        color: "0.05 0.05 0.06 1.0"
    collision:
      mesh:
        package: kuka_robot_descriptions
        path: meshes/lbr_iisy15_r930/collision/base_link.stl

  link_1:
    visual:
      mesh:
        package: kuka_robot_descriptions
        path: meshes/lbr_iisy15_r930/visual/link_1.stl
      material:
        name: "KukaPearlWhite"
        color: "0.945 0.92 1.0 1.0"
    collision:
      mesh:
        package: kuka_robot_descriptions
        path: meshes/lbr_iisy15_r930/collision/link_1.stl

  link_2:
    visual:
      mesh:
        package: kuka_robot_descriptions
        path: meshes/lbr_iisy15_r930/visual/link_2.stl
      material:
        name: "KukaOrange"
        color: "0.945 0.92 1.0 1.0"
    collision:
      mesh:
        package: kuka_robot_descriptions
        path: meshes/lbr_iisy15_r930/collision/link_2.stl

  link_3:
    visual:
      mesh:
        package: kuka_robot_descriptions
        path: meshes/lbr_iisy15_r930/visual/link_3.stl
      material:
        name: "KukaOrange"
        color: "0.945 0.92 1.0 1.0"
    collision:
      mesh:
        package: kuka_robot_descriptions
        path: meshes/lbr_iisy15_r930/collision/link_3.stl

  link_4:
    visual:
      mesh:
        package: kuka_robot_descriptions
        path: meshes/lbr_iisy15_r930/visual/link_4.stl
      material:
        name: "KukaOrange"
        color: "0.945 0.92 1.0 1.0"
    collision:
      mesh:
        package: kuka_robot_descriptions
        path: meshes/lbr_iisy15_r930/collision/link_4.stl

  link_5:
    visual:
      mesh:
        package: kuka_robot_descriptions
        path: meshes/lbr_iisy15_r930/visual/link_5.stl
      material:
        name: "KukaOrange"
        color: "0.945 0.92 1.0 1.0"
    collision:
      mesh:
        package: kuka_robot_descriptions
        path: meshes/lbr_iisy15_r930/collision/link_5.stl

  link_6:
    visual:
      mesh:
        package: kuka_robot_descriptions
        path: meshes/lbr_iisy15_r930/visual/link_6.stl
      material:
        name: "KukaOrange"
        color: "0.945 0.92 1.0 1.0"
    collision:
      mesh:
        package: kuka_robot_descriptions
        path: meshes/lbr_iisy15_r930/collision/link_6.stl

