# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration, max_jerk]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]

# Easiest way to slow down the robot is to decrease the velocity and acceleration scaling factors
default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0
joint_limits:
  joint_1:
    has_acceleration_limits: false
    has_effort_limits: false
    has_position_limits: true
    has_velocity_limits: true
    has_jerk: false
    max_position: !degrees 185.0
    max_velocity: !degrees 120.0
    min_position: !degrees -185.0
    max_effort: 7290
  joint_2:
    has_acceleration_limits: false
    has_effort_limits: false
    has_position_limits: true
    has_velocity_limits: true
    has_jerk: false
    max_position: !degrees -5.0
    max_velocity: !degrees 115.0
    min_position: !degrees -140.0
    max_effort: 8910
  joint_3:
    has_acceleration_limits: false
    has_effort_limits: false
    has_position_limits: true
    has_velocity_limits: true
    has_jerk: false
    max_position: !degrees 168.0
    max_velocity: !degrees 112.0
    min_position: !degrees -120.0
    max_effort: 6988.84717
  joint_4:
    has_acceleration_limits: false
    has_effort_limits: false
    has_position_limits: true
    has_velocity_limits: true
    has_jerk: false
    max_position: !degrees 350.0
    max_velocity: !degrees 179.0
    min_position: !degrees -350.0
    max_effort: 2274.29199
  joint_5:
    has_acceleration_limits: false
    has_effort_limits: false
    has_position_limits: true
    has_velocity_limits: true
    has_jerk: false
    max_position: !degrees 125.0
    max_velocity: !degrees 172.0
    min_position: !degrees -125.0
    max_effort: 1398.30298
  joint_6:
    has_acceleration_limits: false
    has_effort_limits: false
    has_position_limits: true
    has_velocity_limits: true
    has_jerk: false
    max_position: !degrees 350.0
    max_velocity: !degrees 220.0
    min_position: !degrees -350.0
    max_effort: 781.554626
