kinematics:
  link_1:
    x: 0.0
    y: 0.0
    z: 0.4
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  link_2:
    x: 0.025
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  link_3:
    x: 0.315
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  link_4:
    x: 0.0
    y: 0.0
    z: 0.035
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  link_5:
    x: 0.365
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  link_6:
    x: 0.080
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

