inertia_parameters:
  base_link_mass: 0.0
  link_1_mass: 0.0
  link_2_mass: 0.0
  link_3_mass: 0.0
  link_4_mass: 0.0
  link_5_mass: 0.0
  link_6_mass: 0.0

  links:
    base_link:
      ixx: 0.0
      iyy: 0.0
      izz: 0.0
    link_1:
      ixx: 0.0
      iyy: 0.0
      izz: 0.0
    link_2:
      ixx: 0.0
      iyy: 0.0
      izz: 0.0
    link_3:
      ixx: 0.0
      iyy: 0.0
      izz: 0.0
    link_4:
      ixx: 0.0
      iyy: 0.0
      izz: 0.0
    link_5:
      ixx: 0.0
      iyy: 0.0
      izz: 0.0
    link_6:
      ixx: 0.0
      iyy: 0.0
      izz: 0.0
